{{- if and .Values.serviceAccount.create .Values.autoDiscovery }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: auto-discovery-rolebinding
  labels:
      {{- include "featbit-metadata-labels-common" . | nindent 4 }}
  annotations:
      {{- include "featbit-metadata-annotations-common" . | nindent 4 }}
roleRef:
  kind: Role
  name: auto-discovery-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "featbit.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}