{{- if .Values.autoDiscovery }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: auto-discovery-role
  labels:
      {{- include "featbit-metadata-labels-common" . | nindent 4 }}
  annotations:
      {{- include "featbit-metadata-annotations-common" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
{{- end }}
