{{- if .Values.das.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "featbit.fullname" . }}-das-hpa
  labels:
    {{- include "featbit-metadata-labels-common" . | nindent 4 }}
  annotations:
    {{- include "featbit-metadata-annotations-common" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "featbit.fullname" . }}-das
  minReplicas: {{ .Values.das.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.das.autoscaling.maxReplicas }}
  metrics:
    {{- with .Values.das.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
{{- end }}
