{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "featbit.serviceAccountName" . }}
  labels:
    {{- include "featbit-metadata-labels-common" . | nindent 4 }}
  annotations:
    {{- include "featbit-metadata-annotations-common" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
