apiVersion: v2
name: featbit
description: A Helm chart for FeatBit feature flags service

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.7-pre2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.5.0"

kubeVersion: ">=1.23-0"

home: https://github.com/featbit/featbit

sources:
  - https://github.com/featbit/charts

dependencies:
  - name: mongodb
    version: 13.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 17.0.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: kafka
    repository: https://charts.bitnami.com/bitnami
    version: 23.0.7
    condition: kafka.enabled
  - name: clickhouse
    repository: https://charts.bitnami.com/bitnami
    version: 3.6.8
    condition: clickhouse.enabled

maintainers:
  - name: featbit.master
    email: featbit.master@gmail.com


